version: '3.8'

services:
  shopify-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - prisma:/app/prisma
    command: sh -c "npx prisma migrate reset --force && npm run docker-start"

volumes:
  prisma:
